"""init

Revision ID: b75d14548ae9
Revises: 
Create Date: 2020-11-16 19:05:12.885853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75d14548ae9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copyright_holder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('legal_name', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copyright_holder_email'), 'copyright_holder', ['email'], unique=True)
    op.create_index(op.f('ix_copyright_holder_legal_name'), 'copyright_holder', ['legal_name'], unique=False)
    op.create_index(op.f('ix_copyright_holder_username'), 'copyright_holder', ['username'], unique=True)
    op.create_index(op.f('ix_copyright_holder_website'), 'copyright_holder', ['website'], unique=True)
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('copyright_holder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['copyright_holder_id'], ['copyright_holder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_name'), 'collection', ['name'], unique=False)
    op.create_index(op.f('ix_collection_slug'), 'collection', ['slug'], unique=False)
    op.create_table('piece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_piece_name'), 'piece', ['name'], unique=False)
    op.create_index(op.f('ix_piece_slug'), 'piece', ['slug'], unique=False)
    op.create_index(op.f('ix_piece_timestamp'), 'piece', ['timestamp'], unique=False)
    op.create_index(op.f('ix_piece_type'), 'piece', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_piece_type'), table_name='piece')
    op.drop_index(op.f('ix_piece_timestamp'), table_name='piece')
    op.drop_index(op.f('ix_piece_slug'), table_name='piece')
    op.drop_index(op.f('ix_piece_name'), table_name='piece')
    op.drop_table('piece')
    op.drop_index(op.f('ix_collection_slug'), table_name='collection')
    op.drop_index(op.f('ix_collection_name'), table_name='collection')
    op.drop_table('collection')
    op.drop_index(op.f('ix_copyright_holder_website'), table_name='copyright_holder')
    op.drop_index(op.f('ix_copyright_holder_username'), table_name='copyright_holder')
    op.drop_index(op.f('ix_copyright_holder_legal_name'), table_name='copyright_holder')
    op.drop_index(op.f('ix_copyright_holder_email'), table_name='copyright_holder')
    op.drop_table('copyright_holder')
    # ### end Alembic commands ###
